### ISSUE TITLE
Can't run it (401 or 429 error)

### ISSUE THREAD

**Issue by seva100** [Guitaricet/howto#3]
Thanks for a great tool!

Unfortunately, I was unable to give it a try: it throws _401 Unauthorized_ error if I just run `howto <prompt>` (after providing the API key at the first run), or _429 Too Many Requests_ if I execute it with API key provided in the same command: `OPENAI_API_KEY=... howto <prompt>`. Is that expected or am I doing something wrong?

**Comment by Guitaricet** [comment]
Most likely, you don't have a credit card attached to your OpenAI account.

**Comment by seva100** [comment]
You were right. I attached a credit card to the account and created a new API key, after which it worked. Thanks!
