### ISSUE TITLE
secret not found in keyring

### ISSUE THREAD

**Issue by azsh1725** [Guitaricet/howto#4]
Hi!

I have installed your utility, and I have also added the environment variable OPENAI_API_KEY and completed the initial setup. However, when I run the utility, I receive the following error: 
```
OpenAI` API key not found. Please run `howto --setup` to set it.
Error getting OpenAI API key:  secret not found in keyring
Error generating command: secret not found in keyring
```

Can you provide troubleshooting tips, pleases?

**Comment by Guitaricet** [comment]
Hi!
Are you using MacOS?
In this case run `howto --setup` to add your openai key to macos keyring. It is a more secure way to store it than in `.bashrc`

If it's not MacOS, please provide the output of `howto -config`

**Comment by azsh1725** [comment]
No, i use Linux (Ubuntu)

Output for --config:
```
OS: linux
Config path: /home/azik/.howto/config.json
Config:
{
  "version": "",
  "model": "gpt-3.5-turbo",
  "shell": "bash",
  "max_tokens": 512,
  "system_message": "You are a CLI tool that converts user requests to shell commands or short scripts. E.g., for `bash command to tar file without compression:`, you should reply `tar -cf file.tar file`. Avoid natural language. If you have to use it, be extremely concise. Less than 5 words."
}
```

**Comment by Guitaricet** [comment]
Fixed in https://github.com/Guitaricet/howto/releases/tag/v2.0.2

**Comment by azsh1725** [comment]
It worked, thanks!
